### ISSUE TITLE
Potential Bug with PiperPort assigned to Mappings

### ISSUE THREAD

**Issue by LucaBonfiglioli** [eyecan-ai/pipelime-python#125]
* pipelime version: 1.6.2
* Python version: 3.10
* Operating System: Ubuntu 20.04

### Description

Pipelime piper ports don't work with `Mapping`s, only with `Sequence`s.

### What I Did

Contents of `merge.py`

```python
import typing as t

import pipelime.commands.interfaces as plint
import pipelime.piper as ppr
import pydantic as pyd


class MergeList(ppr.PipelimeCommand, title="merge-list"):
    inputs: t.Sequence[plint.InputDatasetInterface] = pyd.Field(
        [], piper_port=ppr.PiperPortType.INPUT
    )
    output: plint.OutputDatasetInterface = plint.OutputDatasetInterface.pyd_field(
        piper_port=ppr.PiperPortType.OUTPUT
    )

    def run(self) -> None:
        pass


class MergeMap(ppr.PipelimeCommand, title="merge-map"):
    inputs: t.Mapping[str, plint.InputDatasetInterface] = pyd.Field(
        {}, piper_port=ppr.PiperPortType.INPUT
    )
    output: plint.OutputDatasetInterface = plint.OutputDatasetInterface.pyd_field(
        piper_port=ppr.PiperPortType.OUTPUT
    )

    def run(self) -> None:
        pass
```

Contents of `dag.yml`

```yaml
nodes:
    clone1:
        clone:
            input: /path/to/input1
            output: /path/to/clone1

    clone2:
        clone:
            input: /path/to/input2
            output: /path/to/clone2

    merge-list:
        merge-list:
            inputs:
                - /path/to/clone1
                - /path/to/clone2
            output: /path/to/merge-list

    merge-map:
        merge-map:
            inputs:
                alice: /path/to/clone1
                bob: /path/to/clone2
            output: /path/to/merge-map
```

Output of `pipelime -m merge.py draw -c dag.yml`
![tmpfr9ix8r1](https://github.com/eyecan-ai/pipelime-python/assets/6567253/6f57fc6a-dfb2-4c1f-a9c0-1a2f697ede00)

It does not connect the outputs of `clone1` and `clone2` to the inputs of `merge-map`, but it does so to `merge-list`
